// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} bg-slate-900 min-h-screen antialiased`}> 
//         <header className="fixed top-0 left-0 right-0 z-50 border-b border-slate-700/50 bg-slate-900/95 backdrop-blur-sm">
//           <div className="w-full px-8 h-16 flex items-center justify-between">
//             <Link href="/" className="font-bold text-xl text-white hover:text-violet-400 transition-colors">
//               Durham Room
//             </Link>
//             <nav className="flex items-center gap-6">
//               <Link href="/login" className="text-sm text-white hover:text-violet-400 transition-colors font-medium">登录</Link>
//               <Link href="/slots" className="text-sm text-white hover:text-violet-400 transition-colors font-medium">可预约时间</Link>
//               <Link href="/bookings" className="text-sm text-white hover:text-violet-400 transition-colors font-medium">我的预约</Link>
//             </nav>
//           </div>
//         </header>
//         <main>
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientHeader from "@/components/ClientHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-slate-900 min-h-screen antialiased`}> 
        {/* Client-side header with authentication-based navigation */}
        <ClientHeader />
        {/* 主内容区 - 强制使用150px顶部间距解决遮挡问题 */}
        <main style={{ marginTop: '150px' }}>
          {children}
        </main>
      </body>
    </html>
  );
}